<a href="https://colab.research.google.com/github/anujsaxena/Python/blob/main/Collection_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Python Collections**

**Tuple**

Tuple can store multiple items in a single variable. It is immutable and supports duplicates also

In [ ]:
t=("delhi","noida","dehradun","mumbai")
print(t)
print(type(t))

In [ ]:
print(len(t))

In [ ]:
print(t[0])

In [ ]:
t1=t[0]
print(type(t1))
print(len(t1))

In [ ]:
t=(1,2,3,4,5,6,7,8,9)
print(t)
print(type(t))
print(len(t))

In [ ]:
t=(True, False, False, True)
print(t)
print(type(t))
print(len(t))

# A tuple can store numbers, strings, boolean or a mix of all

In [ ]:
t=(True,1,2,3,4,"Delhi","Mumbai",6,7,False)
print(t)
print(type(t))
print(len(t))

In [ ]:
t=(1,2,3,4,5,6,7)
t[0]=9
print(t)

In [ ]:
t+=(2,3,4,5,6,7,8)
print(t)

In [ ]:
t1=t[0:3]
print(t1)

In [ ]:
t1=t[3:]
print(t1)

# **Delete Tuple**


In [ ]:
print(t1)
del t1

In [ ]:
print(t1)

In [ ]:
print(t)

In [ ]:
t1=t
t=[]


In [ ]:
print(t)

In [ ]:
t=t1
print(t)

In [ ]:
print(t[2])
t[2]=[]

In [ ]:
del t[2]
print(t)

In [ ]:
del t
print(t)

In [ ]:
t=t1
print(t)

In [ ]:
t=t[0:3]
print(t)

# **List**

This article was published as a part of the Data Science Blogathon.
Python Lists Refresher
The list is one of the most widely used data types in Python. A Python List can be easily identified by square brackets [ ]. Lists are used to store the data items where each data item is separated by a comma (,). A Python List can have data items of any data type, be it an integer type or a boolean type.

One of the leading reasons why lists are being widely used is that Lists are mutable. Being mutable means, any data item of a List can be replaced by any other data item. This makes Lists different from Tuples, which are also used for storing data items but are immutable.

In [ ]:
l=[2,3,4,5,1,6,7,8,9]
print(l)
print(type(l))

# Indexing in a List are of two types:

1. Positive Indexing – Here the indexing starts from 0, moving from left to right.

2. Negative Indexing – In this, the indexing starts from right to left and the rightmost element has an index value of -1.

In [ ]:
l=[4,3,5,6,2,1,7,9,8,10]
print(l[0])

for i in l:
  print(i)


# **Negative indexing**

In [ ]:
print("First element: {}".format(l[-1]))
for i in range(-1,-(len(l)+1),-1):
  print(l[i], end=",")
  

# **Deleting**

In [ ]:
l1=l
del l
print(l)

In [ ]:
l=l1
l=[]
print(l)

In [ ]:
l=l1
print(l)
l[2]=[]
print(l)

In [ ]:
l.remove([])
print(l)

In [ ]:
n=int(input("Enter a number to be removed from the list"))
if n in l:
  l.remove(n)
print(l)

#**Remove all the occurances of an element from a list**

In [ ]:
l=[1,2,3,2,4,5,7,6,8,1,4,5,7,6,8,9,2]
print(l)
n=int(input("Enter a number to be removed from the list "))
while n in l:
  l.remove(n)
print(l)

In [ ]:
l=[1,2,3,2,4,5,7,6,8,1,4,5,7,6,8,9,2]
print(l)
ls = set(l)
print(ls)
l=list(ls)
print(l)

**# Delete using index**

In [ ]:
l=[1,2,3,2,4,5,7,6,8,1,4,5,7,6,8,9,2]
print(l)
l1=l[1]
del l[1]
print("Delete element at index 1 : {0},\n{1}".format(l1,l))
del l[-1]
print("Delete element at index -1 : {}".format(l))

# Pop out the element

In [ ]:
print(l)
l.pop(0)
print(l)
l.pop(-1)
print(l)

# Removing a slice

Elemements can be removed in a range by either giving a start and stop range with : in between (example - l(2:4)). All the elemnts from a starting point can be removved by omitting the stop range (example: l(2:)).
The indexing can be from reverse order also like: l(-2:)

In [ ]:
l=[1,2,3,2,4,5,7,6,8,1,4,5,7,6,8,9,2]
print(l)
ls=l[0:3]
print(ls)
del l[0:3]
print("Delete from 0 to 3 :{}".format(l))
del l[6:]
print("Delete from 6 till end :{}".format(l))
del l[-3:]
print("Delete from -3 till beginning :{}".format(l))

# Remove all the elements

In [ ]:
l=[1,2,3,2,4,5,7,6,8,1,4,5,7,6,8,9,2]
print(l)
l.clear()
print(l)

Append

In [ ]:
a = [0, 1, 1, 2, 3, 5, 8, 13]
b = [5., "girl", 2+0j, "horse", 21]
c =a+b
print(c)

In [ ]:
c[0]=c[0]+4
print(c)

# **Range**

In [ ]:
a=range(3,10)
print(a)

In [ ]:
for i in a:
  print(i, end=",")

In [ ]:
for i in range(1,10,3):
  print(i, end=",")

Exchange the element

In [ ]:
l=[1,3,4,5,6,7,8,9,10,11,12]
print(l)

In [ ]:
l[0],l[-1]=l[-1],l[0]
print(l)

# **Multidimensional list**

In [ ]:
l=[[1,2,3,4],["a","b","c"],[True, False, True]]
print(l)

In [ ]:
l.append(["hello","how are","you"])
print(l)

In [ ]:
print(l[0][0])

In [ ]:
print(l[0][1])

In [ ]:
print(l[1][0])

In [ ]:
print(l[3][2])

# **Extend**

In [ ]:
l[0].extend([7,4,9,10])
print(l)

In [ ]:
l[0].extend(["piyush","nikki"])
print(l)

In [ ]:
print(l[0][10])

In [ ]:
print(len(l[0]))

In [ ]:
for i in range(len(l)):
  for j in range(len(l[i])):
    print(l[i][j],end=" ")
  print()

# **Arrays**
From the prvious knolwedge of arrays we know that "Arrays are a linear collection of similar data types". In python Array are like lists only which hold a group of items. Array stores items within square brackets and can store non-unique values. To create an array we need a module. One can use Numpy or array module for the same.

To create an array using array module one has to give the value type. The syntax is :

ar = array.array(<'value type'>, <[data]>)

In [ ]:
import array
ar = array.array('i',[1,2,3,4,5])
print(ar)
for i in ar:
  print(i)


In [ ]:
import array
ar = array.array('u',['a','b','c'])
print(ar)
for j in ar:
  print(j)


In [ ]:
import array
ar = array.array('d',[2,4,5,6,7])
print(ar)
for i in ar:
  print(i)


In [ ]:
import array
ar = array.array('b',[0,1,0,0,1])
print(ar)
for i in ar:
  print(i)

In [ ]:
import array
ar = array.array('b',[True,False,True,True,False])
print(ar)
for i in ar:
  print(i)

In [ ]:
l=[1,2,3,4,5,6,7,8,9,10]
ar = array.array('i',l)
print(ar)
for i in ar:
  print(i)

# **Creating array using Numpy**



In [ ]:
import numpy as np

ar = np.array([2,3,5,1,6,8,7,9])
print(ar)
print(type(ar))

# **Converting a list into an array**

In [ ]:
l =[3,1,8,9,10]
print(l)
print(type(l))
ar= np.array(l)
print(ar)
print(type(ar))

# **linspace**

The linspace function creates an array of   evenly spaced points between a starting point and an ending point. 

The form of the function is linspace(start, stop, N). If the third argument N is omitted, then N=50.


In [ ]:
import numpy as np
l =np.linspace(1,10)
print(l)

In [ ]:
import numpy as np
l =np.linspace(1,10,10)
print(l)

In [ ]:
ar = array.array('d',l)
print(ar)

In [ ]:
for i in ar:
  print(i, end=",")

# **logspace**

NumPy also has a closely related function logspace that produces evenly spaced points on a logarithmically spaced scale. The arguments are the same as those for linspace except that start and stop refer to a power of 10. That is, the array starts at 10^start  and 10^stop .

In [ ]:
lg = np.logspace(1,3,10)
print(lg)

In [ ]:
ar = array.array('d',lg)
print(ar)

In [ ]:
for i in ar:
  print(i)

In [ ]:
print(ar[2:5])

In [ ]:
arr= ar[2:5]
for i in arr:
  print(i)

# **arange**

The third way arrays can be created is using the NumPy arange function, which is similar to the Python range function for creating lists. The form of the function is arange(start, stop, step). If the third argument is omitted step=1. If the first and third arguments are omitted, then start=0and step=1.

In [ ]:
n=np.arange(1,10,2)
print(n)

In [ ]:
print(type(n))

In [ ]:
arr=array.array('i',n)
print(arr)

In [ ]:
for i in arr:
  print(i)

In [ ]:
z=np.zeros(6)
print(z)

In [ ]:
print(type(z))

In [ ]:
o=np.ones(9)
print(o,end=",")
print(type(o))

# **Mathematical operations**

In [ ]:
a = np.linspace(-1., 5, 7)
print(a)


In [ ]:
ar= a*2
print(ar)

In [ ]:
ar = a+2
print(ar)

In [ ]:
ar = a/2
print(ar)

In [ ]:
ar = a**2
print(ar)

# **Multidimensioanl arrays**
We can use vertical stack to create an n-dimensional array

In [ ]:
a = np.array([1,2,3])
print(a)
b = np.array([4,5,6])
print(b)
print()
c = np.vstack((a, b))
print(c)
print(c.shape)

[1 2 3]
[4 5 6]

[[1 2 3]
 [4 5 6]]
(2, 3)


# **Concatinating array**
We can use horizontal stack to concatenate the arrays

In [ ]:
a = np.array([1,2,3])
print(a)
b = np.array([4,5,6])
print(b)
print()
c = np.hstack((a, b))
print(c)
print(c.shape)

[1 2 3]
[4 5 6]

[1 2 3 4 5 6]
(6,)


# **Difference btween List and array**

For an array we need a seperate module but List is inbuilt, it does not require a seperate module.

Array can store data more efficiently than List

Arrays are good for mathematical opeartions. A List cannot direclty handle a mathematical operation. Let us see with an example:

In [ ]:
l=[3,6,8,9,10]
ar = np.array([2,7,8,9,10])
opr = ar/2
print(opr)
opl=l/2
print(op1)


# **Strings**

In [ ]:
S="welcome"
print(S)

In [ ]:
for i in S:
  print(i)

In [ ]:
print(type(S))

In [ ]:
print(len(S))

In [ ]:
if 'o' in S:
  print('Found')
else:
  print('Not present')

# **Multiple lines**



In [ ]:
s ='''Welcome to the world pf computing
let us learn python.
join us today'''
print(s)
print(type(s))

In [ ]:
if 'join' in s:
  print('join us')
else:
  print('no issues')

In [ ]:
print(len(s))