<a href="https://colab.research.google.com/github/anujsaxena/Python/blob/main/ML_TUT_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Various Ml Algorithms on real dataset**

In [3]:
import pandas
import numpy as np
import matplotlib.pyplot as plt
from sklearn import model_selection
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split

def split_dataset(dataset, train_percentage, feature_headers, target_header):
  # Split dataset into train and test dataset
    train_x, test_x, train_y, test_y = train_test_split(dataset[feature_headers], dataset[target_header],
                                                        train_size=train_percentage)
    return train_x, test_x, train_y, test_y

def handel_missing_values(dataset, missing_values_header, missing_label):
  return dataset[dataset[missing_values_header] != missing_label]

HEADERS = ["S_LI_1","LS_LI_2","PA_Phoneme","SWE_SS","VSR_LR","CN_PV","CL_Add","CL_Sub","RG_Series","VSR_LR","PA_Rhyme","CL_BMS","VMI_MS","VSR_RAN","PA_DE","CL_WP","CG_Spellings","HW_Legibility","PM_RFaudio","CG_STMLTM","Loudness","Class"]
INPUT_PATH = "data2000.csv"
dataset = pandas.read_csv(INPUT_PATH)
x=dataset
df = pandas.read_csv(INPUT_PATH, na_values='NaN', keep_default_na=False)
print("Any empty cells")
print(np.count_nonzero(df.isnull().values))



Any empty cells
0


In [4]:
train_x, test_x, train_y, test_y = split_dataset(dataset, 0.7, HEADERS[1:-1], HEADERS[-1])
print(HEADERS[-1])
print(HEADERS[1:-1])

Class
['LS_LI_2', 'PA_Phoneme', 'SWE_SS', 'VSR_LR', 'CN_PV', 'CL_Add', 'CL_Sub', 'RG_Series', 'VSR_LR', 'PA_Rhyme', 'CL_BMS', 'VMI_MS', 'VSR_RAN', 'PA_DE', 'CL_WP', 'CG_Spellings', 'HW_Legibility', 'PM_RFaudio', 'CG_STMLTM', 'Loudness']


In [5]:
null_columns=x.columns[x.isnull().any()]
#print(dataset.apply(lambda x: x.count(), axis=1))
print(x[x.isnull().any(axis=1)][null_columns].head())

Empty DataFrame
Columns: []
Index: []


In [6]:
# shape
print(dataset.shape)
# display data
print(dataset)
# head
print(dataset.head(21))

(2001, 22)
      LS_LI_1  LS_LI_2  PA_Phoneme  ...  CG_STMLTM  Loudness       Class
0           1        1           0  ...          1        66    Dyslexia
1           1        0           0  ...          1        66    Dyslexia
2           0        0           0  ...          1        70    Dyslexia
3           0        1           0  ...          1        67    Dyslexia
4           1        1           0  ...          1        73  Dysgraphia
...       ...      ...         ...  ...        ...       ...         ...
1996        0        0           0  ...          1        70          DD
1997        1        1           1  ...          1        80  Dysgraphia
1998        1        1           0  ...          0        71         DD6
1999        1        1           1  ...          0        67  Dysgraphia
2000        1        1           1  ...          1        85          ND

[2001 rows x 22 columns]
    LS_LI_1  LS_LI_2  PA_Phoneme  ...  CG_STMLTM  Loudness       Class
0         1     

In [7]:
# descriptions
print(dataset.describe())

           LS_LI_1      LS_LI_2  ...    CG_STMLTM     Loudness
count  2001.000000  2001.000000  ...  2001.000000  2001.000000
mean      0.757621     0.664668  ...     0.812594    69.068966
std       0.428629     0.472225  ...     0.390335     5.598771
min       0.000000     0.000000  ...     0.000000    55.000000
25%       1.000000     0.000000  ...     1.000000    66.000000
50%       1.000000     1.000000  ...     1.000000    70.000000
75%       1.000000     1.000000  ...     1.000000    71.000000
max       1.000000     1.000000  ...     1.000000    87.000000

[8 rows x 21 columns]


In [8]:
# class distribution
print(dataset.groupby('Class').size())

Class
DD             209
DD2             92
DD3            144
DD4            164
DD5             18
DD6             59
DD7             24
DD8              2
Dycalculia       6
Dyscalculia     40
Dysgraphia     515
Dyslexia       343
ND             358
Stammer         12
stammer         15
dtype: int64


In [9]:
array = dataset.values
X = array[:,0:19]
y = array[:,21]
print(X)
print()
print(y)

[[1 1 0 ... 0.5 0.5 0.9]
 [1 0 0 ... 1.0 1.0 0.6]
 [0 0 0 ... 1.0 1.0 0.9]
 ...
 [1 1 0 ... 0.5 0.5 0.2]
 [1 1 1 ... 1.0 0.5 0.8]
 [1 1 1 ... 1.0 1.0 1.0]]

['Dyslexia' 'Dyslexia' 'Dyslexia' ... 'DD6' 'Dysgraphia' 'ND']


# **KNN**

In [12]:
# Make predictions on validation dataset
knn = KNeighborsClassifier()
knn.fit(train_x, train_y)
predictions = knn.predict(test_x)
print("KNN Accuracy score = ",(accuracy_score(test_y, predictions)*100))
print("\nConfusion Matrix \n")
print(confusion_matrix(test_y, predictions))
print("\nClassification Report - KNN\n")
print(classification_report(test_y, predictions))

KNN Accuracy score =  97.50415973377704

Confusion Matrix 

[[ 73   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0  27   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0  41   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0  45   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   3   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0  15   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   2   0   2   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   1   0   0   0]
 [  0   1   0   0   0   0   0   0   5   1   0   7   0   0]
 [  0   0   0   0   0   0   0   0   0 164   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0  99   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0 112   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   2   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   1   0   0]]

Classification Report - KNN

              precision    recall  f1-score   support

          DD       1.00     

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# **Prediction**

In [13]:
for i in range(0, len(predictions)):
        print("Feature :: {}  Class in :: {}".format(list(X)[i], predictions[i]))

Feature :: [1 1 0 1 1 1 1 1 1 1 0.8 0.8 0.9 0.6 0.8 1.0 0.5 0.5 0.9]  Class in :: Dysgraphia
Feature :: [1 0 0 1 0 1 1 0 1 1 0.5 0.8 1.0 0.6 0.8 1.0 1.0 1.0 0.6]  Class in :: Dyslexia
Feature :: [0 0 0 1 1 1 1 1 1 1 1.0 1.0 0.9 0.4 1.0 1.0 1.0 1.0 0.9]  Class in :: Dysgraphia
Feature :: [0 1 0 1 1 1 0 0 1 1 0.5 0.7 0.9 0.6 0.8 1.0 1.0 0.5 0.6]  Class in :: DD
Feature :: [1 1 0 0 0 1 1 1 0 1 0.5 0.8 0.8 1.0 0.8 1.0 0.5 0.5 0.8]  Class in :: Dysgraphia
Feature :: [1 1 0 0 0 0 1 1 0 0 0.0 0.2 0.8 0.0 0.0 0.0 0.0 0.0 0.4]  Class in :: ND
Feature :: [1 1 0 0 0 1 1 1 0 0 0.6 0.8 0.8 0.5 0.5 1.0 0.0 0.0 0.6]  Class in :: ND
Feature :: [1 0 0 1 0 1 1 1 1 0 0.4 0.8 0.8 0.4 0.5 0.5 0.0 0.0 0.5]  Class in :: ND
Feature :: [1 1 1 0 0 1 0 1 1 0 0.6 0.8 0.9 0.5 0.8 1.0 0.0 0.5 0.8]  Class in :: Dysgraphia
Feature :: [1 1 1 1 0 1 1 1 0 1 0.5 0.8 0.8 0.8 1.0 1.0 0.5 0.5 0.8]  Class in :: Dyslexia
Feature :: [1 1 1 0 1 1 1 1 1 0 0.5 0.8 0.8 1.0 1.0 1.0 0.5 0.5 0.8]  Class in :: DD
Feature :: [1 0 0 1 1

# **Logistic Regression**

In [14]:
Lr=LogisticRegression()
X_train=train_x
Y_train=train_y
X_validation=test_x
Y_validation=test_y
Lr.fit(X_train, Y_train)
predictions = Lr.predict(X_validation)
print("Logistic Regression Accuracy score = ",(accuracy_score(Y_validation, predictions)*100))

print("\nConfusion Matrix \n")
print(confusion_matrix(Y_validation, predictions))
print("\nClassification Report - LR\n")
print(classification_report(Y_validation, predictions))

for i in range(0, len(predictions)):
        print("Feature :: {}  Class in :: {}".format(list(Y_validation)[i], predictions[i]))


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0

Logistic Regression Accuracy score =  87.18801996672212

Confusion Matrix 

[[ 67   0   2   0   0   0   0   0   0   4   0   0   0   0]
 [  0  12   0   3   0   0   0   0   0   1  11   0   0   0]
 [ 10   0  31   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0  35   0   0   0   0   0   1   9   0   0   0]
 [  0   0   0   0   3   0   0   0   0   0   0   0   0   0]
 [  0   2   2   0   0  11   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   4   0   0   0   0   0   0   0]
 [  0   1   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   3   0   0   0   0   0   0   8   2   0   1   0   0]
 [  0   0   0   0   0   0   0   0   0 151   0  13   0   0]
 [  2   0   0   2   0   0   0   0   0   5  90   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0 112   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   2   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   1   0   0]]

Classification Report - LR

              precision    recall  f1-score   support

          DD 

# **Linear Discriminant Analysis**



In [17]:
Lda = LinearDiscriminantAnalysis()
Lda.fit(X_train, Y_train)
predictions = Lda.predict(X_validation)
print("Linear Discriminant Analysis(LDA) Accuracy score = ",(accuracy_score(Y_validation, predictions)*100))

print("\nConfusion Matrix \n")
print(confusion_matrix(Y_validation, predictions))
print("\nClassification Report - LDA\n")
print(classification_report(Y_validation, predictions))

Linear Discriminant Analysis(LDA) Accuracy score =  87.35440931780366

Confusion Matrix 

[[ 67   0   2   0   0   0   0   0   0   0   4   0   0   0   0]
 [  0  12   0   3   0   0   0   0   0   0   0  11   1   0   0]
 [  8   0  33   0   0   0   0   0   0   0   0   0   0   0   0]
 [  6   0   0  30   0   0   0   0   0   0   0   9   0   0   0]
 [  0   0   0   0   3   0   0   0   0   0   0   0   0   0   0]
 [  1   2   0   0   0  11   0   0   1   0   0   0   0   0   0]
 [  0   0   0   0   0   0   4   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   1   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   1   0   0  11   0   0   2   0   0]
 [  0   0   0   0   0   0   0   0   0   0 151   0  13   0   0]
 [  2   0   0   2   0   0   0   0   0   0   0  95   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0 106   0   6]
 [  0   0   0   0   0   0   0   0   0   0   0   0   2   0   0]
 [  0   0   0   0   0   0   

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1

In [18]:
for i in range(0, len(predictions)):
        print("Feature :: {}  Class in :: {}".format(list(Y_validation)[i], predictions[i]))

Feature :: Dysgraphia  Class in :: Dysgraphia
Feature :: Dyslexia  Class in :: Dyslexia
Feature :: Dysgraphia  Class in :: Dysgraphia
Feature :: DD  Class in :: DD
Feature :: Dysgraphia  Class in :: Dysgraphia
Feature :: ND  Class in :: stammer
Feature :: ND  Class in :: ND
Feature :: ND  Class in :: ND
Feature :: Dysgraphia  Class in :: Dysgraphia
Feature :: Dyslexia  Class in :: Dyslexia
Feature :: DD  Class in :: DD
Feature :: Dyscalculia  Class in :: Dyscalculia
Feature :: Dyslexia  Class in :: Dyslexia
Feature :: DD  Class in :: DD
Feature :: Dysgraphia  Class in :: Dysgraphia
Feature :: Dyslexia  Class in :: DD
Feature :: ND  Class in :: stammer
Feature :: Dysgraphia  Class in :: Dysgraphia
Feature :: DD  Class in :: DD
Feature :: DD2  Class in :: Dyslexia
Feature :: Dyslexia  Class in :: DD
Feature :: Dysgraphia  Class in :: Dysgraphia
Feature :: DD  Class in :: DD
Feature :: DD4  Class in :: DD4
Feature :: DD4  Class in :: DD4
Feature :: Dyslexia  Class in :: Dyslexia
Feature :

# **Decision Tree Classifier**

In [19]:
CT = DecisionTreeClassifier()
CT.fit(X_train, Y_train)
predictions = CT.predict(X_validation)
print("Decision Tree Classifier(CART) Accuracy score = ",(accuracy_score(Y_validation, predictions)*100))

print("\nConfusion Matrix \n")
print(confusion_matrix(Y_validation, predictions))
print("\nClassification Report - CART\n")
print(classification_report(Y_validation, predictions))

Decision Tree Classifier(CART) Accuracy score =  98.83527454242929

Confusion Matrix 

[[ 73   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0  27   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0  41   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0  45   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   3   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0  15   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   4   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   1   0   0   0   0   0   0]
 [  0   1   0   0   0   0   0   0  11   0   0   2   0   0]
 [  0   0   0   0   0   0   2   0   0 162   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0  99   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0 112   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   1   1   0]
 [  0   0   0   0   0   0   0   0   0   0   0   1   0   0]]

Classification Report - CART

              precision    recall  f1-score   support



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [20]:
for i in range(0, len(predictions)):
        print("Feature :: {}  Class in :: {}".format(list(Y_validation)[i], predictions[i]))

Feature :: Dysgraphia  Class in :: Dysgraphia
Feature :: Dyslexia  Class in :: Dyslexia
Feature :: Dysgraphia  Class in :: Dysgraphia
Feature :: DD  Class in :: DD
Feature :: Dysgraphia  Class in :: Dysgraphia
Feature :: ND  Class in :: ND
Feature :: ND  Class in :: ND
Feature :: ND  Class in :: ND
Feature :: Dysgraphia  Class in :: Dysgraphia
Feature :: Dyslexia  Class in :: Dyslexia
Feature :: DD  Class in :: DD
Feature :: Dyscalculia  Class in :: Dyscalculia
Feature :: Dyslexia  Class in :: Dyslexia
Feature :: DD  Class in :: DD
Feature :: Dysgraphia  Class in :: Dysgraphia
Feature :: Dyslexia  Class in :: Dyslexia
Feature :: ND  Class in :: ND
Feature :: Dysgraphia  Class in :: Dysgraphia
Feature :: DD  Class in :: DD
Feature :: DD2  Class in :: DD2
Feature :: Dyslexia  Class in :: Dyslexia
Feature :: Dysgraphia  Class in :: Dysgraphia
Feature :: DD  Class in :: DD
Feature :: DD4  Class in :: DD4
Feature :: DD4  Class in :: DD4
Feature :: Dyslexia  Class in :: Dyslexia
Feature :: D

# **Gaussiann NB**

In [22]:
nb = GaussianNB()
nb.fit(X_train, Y_train)
predictions = nb.predict(X_validation)
print("Naive Bayes Accuracy score = ",(accuracy_score(Y_validation, predictions)*100))

print("\nConfusion Matrix \n")
print(confusion_matrix(Y_validation, predictions))
print("\nClassification Report - Naive\n")
print(classification_report(Y_validation, predictions))


Naive Bayes Accuracy score =  75.7071547420965

Confusion Matrix 

[[ 67   0   2   4   0   0   0   0   0   0   0   0   0   0]
 [  6   9   0   0   0   0   0   0   0   1   6   0   5   0]
 [ 12   0  29   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0  45   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   3   0   0   0   0   0   0   0   0   0]
 [  3   0   0   0   0  12   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   4   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   1   0   0   0   0   0   0]
 [  0   0   1   0   0   0   0   0  13   0   0   0   0   0]
 [  0   0   0  13   0   0   0   0   0 125  13   0  13   0]
 [  0   0   0  17   0   0   0   0   0   0  70   0  12   0]
 [  0   0   0   0   0   0   0   0   0   0   0  75   0  37]
 [  0   0   0   0   0   0   0   0   0   0   0   0   1   1]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   1]]

Classification Report - Naive

              precision    recall  f1-score   support

          DD       

In [23]:
for i in range(0, len(predictions)):
        print("Feature :: {}  Class in :: {}".format(list(Y_validation)[i], predictions[i]))

Feature :: Dysgraphia  Class in :: Dysgraphia
Feature :: Dyslexia  Class in :: DD4
Feature :: Dysgraphia  Class in :: Dysgraphia
Feature :: DD  Class in :: DD
Feature :: Dysgraphia  Class in :: Dysgraphia
Feature :: ND  Class in :: stammer
Feature :: ND  Class in :: ND
Feature :: ND  Class in :: stammer
Feature :: Dysgraphia  Class in :: Dysgraphia
Feature :: Dyslexia  Class in :: Dyslexia
Feature :: DD  Class in :: DD
Feature :: Dyscalculia  Class in :: Dyscalculia
Feature :: Dyslexia  Class in :: Stammer
Feature :: DD  Class in :: DD
Feature :: Dysgraphia  Class in :: Dysgraphia
Feature :: Dyslexia  Class in :: DD4
Feature :: ND  Class in :: stammer
Feature :: Dysgraphia  Class in :: Dyslexia
Feature :: DD  Class in :: DD
Feature :: DD2  Class in :: Dyslexia
Feature :: Dyslexia  Class in :: DD4
Feature :: Dysgraphia  Class in :: Dysgraphia
Feature :: DD  Class in :: DD
Feature :: DD4  Class in :: DD4
Feature :: DD4  Class in :: DD4
Feature :: Dyslexia  Class in :: Dyslexia
Feature ::

In [27]:
sv = SVC()
sv.fit(X_train, Y_train)
predictions = sv.predict(X_validation)
print("SVM Accuracy score = ",(accuracy_score(Y_validation, predictions)*100))

print("\nConfusion Matrix \n")
print(confusion_matrix(Y_validation, predictions))
print("\nClassification Report - SVM\n")
print(classification_report(Y_validation, predictions))

SVM Accuracy score =  36.938435940099836

Confusion Matrix 

[[  0   0   0   0   0   0   0   0   0  43  30   0   0   0]
 [  0   0   0   0   0   0   0   0   0  14  13   0   0   0]
 [  0   0   0   0   0   0   0   0   0   9  32   0   0   0]
 [  0   0   0   0   0   0   0   0   0  28  17   0   0   0]
 [  0   0   0   0   0   0   0   0   0   3   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   7   8   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   4   0   0]
 [  0   0   0   0   0   0   0   0   0   0   1   0   0   0]
 [  0   0   0   0   0   0   0   0   0   9   1   4   0   0]
 [  0   0   0   0   0   0   0   0   0 155   6   3   0   0]
 [  0   0   0   0   0   0   0   0   0  54  45   0   0   0]
 [  0   0   0   0   0   0   0   0   0  87   3  22   0   0]
 [  0   0   0   0   0   0   0   0   0   1   0   1   0   0]
 [  0   0   0   0   0   0   0   0   0   1   0   0   0   0]]

Classification Report - SVM

              precision    recall  f1-score   support

          DD       0.00    

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [26]:
for i in range(0, len(predictions)):
        print("Feature :: {}  Class in :: {}".format(list(Y_validation)[i], predictions[i]))

Feature :: Dysgraphia  Class in :: Dyslexia
Feature :: Dyslexia  Class in :: Dysgraphia
Feature :: Dysgraphia  Class in :: Dysgraphia
Feature :: DD  Class in :: Dysgraphia
Feature :: Dysgraphia  Class in :: Dysgraphia
Feature :: ND  Class in :: Dysgraphia
Feature :: ND  Class in :: Dysgraphia
Feature :: ND  Class in :: Dysgraphia
Feature :: Dysgraphia  Class in :: Dysgraphia
Feature :: Dyslexia  Class in :: Dyslexia
Feature :: DD  Class in :: Dyslexia
Feature :: Dyscalculia  Class in :: Dysgraphia
Feature :: Dyslexia  Class in :: Dyslexia
Feature :: DD  Class in :: Dyslexia
Feature :: Dysgraphia  Class in :: Dysgraphia
Feature :: Dyslexia  Class in :: Dysgraphia
Feature :: ND  Class in :: Dyslexia
Feature :: Dysgraphia  Class in :: Dysgraphia
Feature :: DD  Class in :: Dyslexia
Feature :: DD2  Class in :: Dyslexia
Feature :: Dyslexia  Class in :: Dysgraphia
Feature :: Dysgraphia  Class in :: Dysgraphia
Feature :: DD  Class in :: Dysgraphia
Feature :: DD4  Class in :: Dyslexia
Feature :