<a href="https://colab.research.google.com/github/anujsaxena/Python/blob/main/numpy_tut.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Numpy**

Numpy is a Python package. It stands for 'Numerical Python'. It is a library consisting of multidimensional array objects and a collection of routines for processing of array. 

Numeric, the ancestor of NumPy, was developed by Jim Hugunin. Another package Numarray was also developed, having some additional functionalities. In 2005, Travis Oliphant created NumPy package by incorporating the features of Num array into Numeric package. There are many contributors to this open source project.

Operations using NumPy 
Using NumPy, a developer can perform the following operations: 

1.	Mathematical and logical operations on arrays. 
2.	Fourier transforms and routines for shape manipulation. 
3.	Operations related to linear algebra. NumPy has in-built functions for linear algebra and random number generation. 

# **Syntax**

It creates an ndarray from any object exposing array interface, or from any method that returns an array.

# **numpy.array(object, dtype=None, copy=True, order=None, subok=False, ndmin=0)**

The above constructor takes the following parameters:

object: 	Any object exposing the array interface method returns an array, or any (nested) sequence 

dtype: 	Desired data type of array, optional 

copy: 	Optional. By default (true), the object is copied 

order: 	C (row major) or F (column major) or A (any) (default) 

subok: 	By default, returned array forced to be a base class array. If true, sub-classes passed through 

ndimin: 	Specifies minimum dimensions of resultant array 



In [1]:
import numpy as np
a= np.array([1,2,3,4,5,6,7])
print(a)
print(a[0]) 
print(a[-1])

[1 2 3 4 5 6 7]
1
7


In [2]:
#Two dimensional
import numpy as np
a = np.array([[1, 2], [3, 4]])
print(a)
print(a[1][0])


[[1 2]
 [3 4]]
3


In [3]:
#Two dimensional
a = np.array([[1, 2, 6], [3, 4]])
print(a)
print(a[1][0])


[list([1, 2, 6]) list([3, 4])]
3


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  


In [4]:
import numpy as np
a=np.array([[1, 2], [3,4],[5,6]], ndmin=2)
print(a)


[[1 2]
 [3 4]
 [5 6]]


In [5]:
import numpy as np
a=np.array([[1, 2], [3,4],[5,6]])
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [6]:
import numpy as np
a=np.array([[1, 2, 8], [3,4],[5,6]], ndmin=2)
print(a)

[[list([1, 2, 8]) list([3, 4]) list([5, 6])]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  


In [7]:
# dtype parameter
import numpy as np
a = np.array([1, 2, 3], dtype=complex)
print(a)

[1.+0.j 2.+0.j 3.+0.j]


In [9]:
dt = np.dtype([('age',np.int8)])
print(dt)
a = np.array([(10,),(20,),(30,)], dtype=dt)
print(a)


[('age', 'i1')]
[(10,) (20,) (30,)]


In [10]:
#reshape array
a=np.array([[1,2,3],[4,5,6]])
print(a)
print(np.shape(a))
a.shape=(3,2)
print('\nSecond\n')
print(a)

[[1 2 3]
 [4 5 6]]
(2, 3)

Second

[[1 2]
 [3 4]
 [5 6]]


In [11]:
a.shape=(1,6)
print('\nSecond\n')
print(a)


Second

[[1 2 3 4 5 6]]


In [12]:
a.shape=(6,1)
print('\nSecond\n')
print(a)


Second

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [13]:
print(np.shape(a))

(6, 1)


In [14]:
a = np.arange(24)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [16]:
print(a.ndim)
print(np.shape(a))

1
(24,)


In [17]:
print('second')
# now reshape it
b = a.reshape(2,4,3)
print(b)

second
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


In [18]:
print('second')
# now reshape it
b = a.reshape(2,3,4)
print(b)

second
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [19]:
print('second')
# now reshape it
b = a.reshape(3,2,4)
print(b)

second
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]]


In [20]:

a = np.empty([4,2], dtype=float)
print(a)


[[4.67299614e-310 1.38338381e-322]
 [2.12199579e-314 3.44620186e-085]
 [3.63460077e+185 1.57230356e+108]
 [8.40995713e-315 0.00000000e+000]]


In [21]:
# Create array having zero values 
a= np.zeros(5, dtype=int)
print(a)


[0 0 0 0 0]


In [22]:
# Create array having zero values 
a= np.zeros(5, dtype=float)
print(a)

[0. 0. 0. 0. 0.]


In [23]:
import numpy as np
x = np.zeros((3,4), dtype=[('x', 'i4'), ('y', 'i4')])
print(x)

[[(0, 0) (0, 0) (0, 0) (0, 0)]
 [(0, 0) (0, 0) (0, 0) (0, 0)]
 [(0, 0) (0, 0) (0, 0) (0, 0)]]


In [24]:
#Array of ones
x = np.ones((2,2), dtype=int)
print(x)

[[1 1]
 [1 1]]


In [26]:
import numpy as np
x = [1,2,3]
print(type(x))
a = np.asarray(x)
print(a)
print(type(a))

<class 'list'>
[1 2 3]
<class 'numpy.ndarray'>


In [28]:
x = [(1,2,3),(4,5)]
print(x)
print(type(x))
a = np.asarray(x,dtype=object)
print(a)
print(type(a))

[(1, 2, 3), (4, 5)]
<class 'list'>
[(1, 2, 3) (4, 5)]
<class 'numpy.ndarray'>


In [29]:
x= np.arange(10, dtype=int)
print(x)


[0 1 2 3 4 5 6 7 8 9]


In [31]:
a = np.array([[1, 2, 3],[4, 5, 6]], float)
print(a)
a=np.zeros((2,3))
print("zeros")
print(a)
a=np.identity(3)
print("identity")
print(a)
a=np.arange(10)
print("arange")
print(a)
print("arange (rows and columns)")
a=np.arange(2,10)
print(a)
print("arange")
a=np.arange(2,3,0.1)
print(a)
print("linspace")
a=np.linspace(1., 4., 6)
print(a)
np.indices((3,3))
print("indices")
print(a)


[[1. 2. 3.]
 [4. 5. 6.]]
zeros
[[0. 0. 0.]
 [0. 0. 0.]]
identity
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
arange
[0 1 2 3 4 5 6 7 8 9]
arange (rows and columns)
[2 3 4 5 6 7 8 9]
arange
[2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9]
linspace
[1.  1.6 2.2 2.8 3.4 4. ]
indices
[1.  1.6 2.2 2.8 3.4 4. ]


In [34]:
c = np.full_like((3,3), 7)
print(c)
print(type(c))

[7 7]
<class 'numpy.ndarray'>


In [35]:
e = np.eye(2)
print(e)  

[[1. 0.]
 [0. 1.]]


In [36]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [38]:
b =a[:2,1:3]
print(b)

[[2 3]
 [6 7]]


In [40]:
b[0,0]=7
print(b)

[[7 3]
 [6 7]]


In [41]:
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [42]:
b = np.array([0, 2, 0, 1])
print(b)

[0 2 0 1]


In [46]:
c = np.arange(4)
print(c)
print(a[np.arange(4), b])

[0 1 2 3]
[ 1  6  7 11]


In [48]:
a[np.arange(4), b] += 10
print(a)


[[21  2  3]
 [ 4  5 26]
 [27  8  9]
 [10 31 12]]


In [50]:
print(a)
d = (a>2)
print(d)

[[21  2  3]
 [ 4  5 26]
 [27  8  9]
 [10 31 12]]
[[ True False  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]]


# **Mathematical operations**

In [53]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)
print(x)
print(y)

[[1. 2.]
 [3. 4.]]
[[5. 6.]
 [7. 8.]]


In [52]:
a =x+y
print(a)

[[ 6.  8.]
 [10. 12.]]


In [54]:
a = np.add(x,y)
print(a)

[[ 6.  8.]
 [10. 12.]]


In [56]:
s = x-y
print(x)
s = np.subtract(x,y)

print("mulitply")
m = x*y
print(m)
m = np.multiply(x,y)
print(m)
print("divide")
d = x/y
print(d)
d = np.divide(x,y)
print(d)

[[1. 2.]
 [3. 4.]]
mulitply
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
divide
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
