<a href="https://colab.research.google.com/github/anujsaxena/Python/blob/main/Transformers_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

https://huggingface.co/docs/transformers/quicktour

In [1]:
!pip install transformers

     |████████████████████████████████| 3.4 MB 14.9 MB/s 
     |████████████████████████████████| 596 kB 76.9 MB/s 
     |████████████████████████████████| 67 kB 6.9 MB/s 
     |████████████████████████████████| 895 kB 70.7 MB/s 
     |████████████████████████████████| 3.3 MB 54.4 MB/s 
  Attempting uninstall: pyyaml
    Found existing installation: PyYAML 3.13
    Uninstalling PyYAML-3.13:
      Successfully uninstalled PyYAML-3.13


In [35]:
from transformers import pipeline
classifier = pipeline('sentiment-analysis')

No model was supplied, defaulted to distilbert-base-uncased-finetuned-sst-2-english (https://huggingface.co/distilbert-base-uncased-finetuned-sst-2-english)


In [36]:
classifier('As Omicron Rages, India, US Cut Isolation Time. Why Are Countries Changing Covid Rules Amid Spike?')

[{'label': 'NEGATIVE', 'score': 0.9850034117698669}]

In [37]:
classifier('India could soon have its first messenger or mRNA vaccine soon, with the near-completion of Phase 3 clinical trials by Gennova Biopharmaceuticals, even as the company also started developing a variant or Omicron-specific vaccine using the same tech platform.')

[{'label': 'NEGATIVE', 'score': 0.997930645942688}]

In [38]:
classifier('विभिन्न तिथियों और प्रकारों के मध्य अंग्रेजी ग्रंथों के अर्क की एक श्रृंखला प्रस्तुत की जाती है, प्रत्येक मार्ग में पाए जाने वाले सभी ऋणशब्दों (फ्रेंच, लैटिन या प्रारंभिक स्कैंडिनेवियाई से) पर टिप्पणी के साथ।')

[{'label': 'NEGATIVE', 'score': 0.8191070556640625}]

In [40]:
classifier('L''Inde pourrait bientôt avoir son premier vaccin messager ou ARNm bientôt, avec la quasi-achèvement des essais cliniques de phase 3 par Gennova Biopharmaceuticals, même si la société a également commencé à développer une variante ou un vaccin spécifique à Omicron en utilisant la même plate-forme technologique.')

[{'label': 'NEGATIVE', 'score': 0.953791081905365}]

In [39]:
results = classifier(["We are very happy to show you the 🤗 Transformers library.",
...            "We hope you don't hate it."])
for result in results:
  print(f"label: {result['label']}, with score: {round(result['score'], 4)}")

label: POSITIVE, with score: 0.9998
label: NEGATIVE, with score: 0.5309


By default, the model downloaded for this pipeline is called “distilbert-base-uncased-finetuned-sst-2-english”. We can look at its model page to get more information about it. It uses the DistilBERT architecture and has been fine-tuned on a dataset called SST-2 for the sentiment analysis task.


Let’s say we want to use another model; for instance, one that has been trained on French data. We can search through the model hub that gathers models pretrained on a lot of data by research labs, but also community models (usually fine-tuned versions of those big models on a specific dataset). Applying the tags “French” and “text-classification” gives back a suggestion “nlptown/bert-base-multilingual-uncased-sentiment”. Let’s see how we can use it.

In [31]:
classifier = pipeline('sentiment-analysis', model="nlptown/bert-base-multilingual-uncased-sentiment")

We will need two classes for this. The first is AutoTokenizer, which we will use to download the tokenizer associated to the model we picked and instantiate it. The second is AutoModelForSequenceClassification (or TFAutoModelForSequenceClassification if you are using TensorFlow), which we will use to download the model itself. Note that if we were using the library on an other task, the class of the model would change.

In [32]:
classifier('Une série d extraits de textes en moyen anglais de dates et de types différents est présentée, avec des commentaires sur tous les emprunts (du français, du latin ou du scandinave ancien) trouvés dans chaque passage.')

[{'label': '4 stars', 'score': 0.46810102462768555}]

In [33]:
classifier('विभिन्न तिथियों और प्रकारों के मध्य अंग्रेजी ग्रंथों के अर्क की एक श्रृंखला प्रस्तुत की जाती है, प्रत्येक मार्ग में पाए जाने वाले सभी ऋणशब्दों (फ्रेंच, लैटिन या प्रारंभिक स्कैंडिनेवियाई से) पर टिप्पणी के साथ।')

[{'label': '4 stars', 'score': 0.41962355375289917}]

In [34]:
classifier('India could soon have its first messenger or mRNA vaccine soon, with the near-completion of Phase 3 clinical trials by Gennova Biopharmaceuticals, even as the company also started developing a variant or Omicron-specific vaccine using the same tech platform.')

[{'label': '2 stars', 'score': 0.32806992530822754}]

# **Star rating**

5 Star = Very positive

4 Star = Positive

3 Star = Neutral

2 Star = Negative

1 Star = Very negative

In [6]:
from transformers import AutoTokenizer, TFAutoModelForSequenceClassification
model_name = "nlptown/bert-base-multilingual-uncased-sentiment"
# This model only exists in PyTorch, so we use the _from_pt_ flag to import that model in TensorFlow.
model = TFAutoModelForSequenceClassification.from_pretrained(model_name, from_pt=True)
tokenizer = AutoTokenizer.from_pretrained(model_name)
classifier = pipeline('sentiment-analysis', model=model, tokenizer=tokenizer)

All PyTorch model weights were used when initializing TFBertForSequenceClassification.

All the weights of TFBertForSequenceClassification were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertForSequenceClassification for predictions without further training.


In [29]:
classifier('India could soon have its first messenger or mRNA vaccine soon, with the near-completion of Phase 3 clinical trials by Gennova Biopharmaceuticals, even as the company also started developing a variant or Omicron-specific vaccine using the same tech platform.')

[{'label': '2 stars', 'score': 0.3280699849128723}]

In [7]:
from transformers import AutoTokenizer, TFAutoModelForSequenceClassification
model_name = "distilbert-base-uncased-finetuned-sst-2-english"
tf_model = TFAutoModelForSequenceClassification.from_pretrained(model_name)
tokenizer = AutoTokenizer.from_pretrained(model_name)

Downloading:   0%|          | 0.00/256M [00:00<?, ?B/s]

Some layers from the model checkpoint at distilbert-base-uncased-finetuned-sst-2-english were not used when initializing TFDistilBertForSequenceClassification: ['dropout_19']
- This IS expected if you are initializing TFDistilBertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFDistilBertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some layers of TFDistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased-finetuned-sst-2-english and are newly initialized: ['dropout_57']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [30]:
classifier('India could soon have its first messenger or mRNA vaccine soon, with the near-completion of Phase 3 clinical trials by Gennova Biopharmaceuticals, even as the company also started developing a variant or Omicron-specific vaccine using the same tech platform.')

[{'label': '2 stars', 'score': 0.3280699849128723}]

# **Using the tokenizer**
We mentioned the tokenizer is responsible for the preprocessing of your texts. First, it will split a given text in words (or part of words, punctuation symbols, etc.) usually called tokens. There are multiple rules that can govern that process (you can learn more about them in the tokenizer summary), which is why we need to instantiate the tokenizer using the name of the model, to make sure we use the same rules as when the model was pretrained.

In [8]:
input = tokenizer('The national capital is likely to witness around 14,000 new Covid-19 cases by Thursday evening, Delhi Health Minister Satyendar Jain said.')

The second step is to convert those tokens into numbers, to be able to build a tensor out of them and feed them to the model. To do this, the tokenizer has a vocab, which is the part we download when we instantiate it with the from_pretrained method, since we need to use the same vocab as when the model was pretrained.

In [9]:
print(input)

{'input_ids': [101, 1996, 2120, 3007, 2003, 3497, 2000, 7409, 2105, 2403, 1010, 2199, 2047, 2522, 17258, 1011, 2539, 3572, 2011, 9432, 3944, 1010, 6768, 2740, 2704, 2938, 20684, 7662, 17136, 2056, 1012, 102], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}


This returns a dictionary string to list of ints. It contains the ids of the tokens, as mentioned before, but also additional arguments that will be useful to the model. 

You can pass a list of sentences directly to your tokenizer. If your goal is to send them through your model as a batch, you probably want to pad them all to the same length, truncate them to the maximum length the model can accept and get tensors back.

In [10]:
tf_batch = tokenizer(
    ["The national capital is likely to witness around 14,000 new Covid-19 cases by Thursday evening", "Delhi Health Minister Satyendar Jain said. 🤗"],
    padding=True,
    truncation=True,
    max_length=512,
    return_tensors="tf"
)

The padding is automatically applied on the side expected by the model (in this case, on the right), with the padding token the model was pretrained with. The attention mask is also adapted to take the padding into account:

In [11]:
print(tf_batch)

{'input_ids': <tf.Tensor: shape=(2, 22), dtype=int32, numpy=
array([[  101,  1996,  2120,  3007,  2003,  3497,  2000,  7409,  2105,
         2403,  1010,  2199,  2047,  2522, 17258,  1011,  2539,  3572,
         2011,  9432,  3944,   102],
       [  101,  6768,  2740,  2704,  2938, 20684,  7662, 17136,  2056,
         1012,   100,   102,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(2, 22), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],
      dtype=int32)>}


In [12]:
for key, value in tf_batch.items():
  print(f"{key}: {value.numpy().tolist()}")

input_ids: [[101, 1996, 2120, 3007, 2003, 3497, 2000, 7409, 2105, 2403, 1010, 2199, 2047, 2522, 17258, 1011, 2539, 3572, 2011, 9432, 3944, 102], [101, 6768, 2740, 2704, 2938, 20684, 7662, 17136, 2056, 1012, 100, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]
attention_mask: [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]


# **Using the model**
Once your input has been preprocessed by the tokenizer, you can send it directly to the model. As we mentioned, it will contain all the relevant information the model needs. If you’re using a TensorFlow model

In [13]:
tf_outputs= tf_model(tf_batch)

In 🤗 Transformers, all outputs are objects that contain the model’s final activations along with other metadata.

In [14]:
print(tf_outputs)

TFSequenceClassifierOutput(loss=None, logits=<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-2.038928 ,  2.0217621],
       [-1.6320709,  1.9502203]], dtype=float32)>, hidden_states=None, attentions=None)


Let’s apply the SoftMax activation to get predictions.

In [15]:
import tensorflow as tf
tf_predictions = tf.nn.softmax(tf_outputs.logits, axis=-1)

All 🤗 Transformers models (PyTorch or TensorFlow) return the activations of the model before the final activation function (like SoftMax) since this final activation function is often fused with the loss.

In [16]:
print(tf_predictions)

tf.Tensor(
[[0.01694504 0.983055  ]
 [0.02705933 0.9729407 ]], shape=(2, 2), dtype=float32)


If you provide the model with labels in addition to inputs, the model output object will also contain a loss attribute:

In [17]:
import tensorflow as tf
tf_outputs = tf_model(tf_batch, labels = tf.constant([1, 0]))
print(tf_outputs)

TFSequenceClassifierOutput(loss=<tf.Tensor: shape=(2,), dtype=float32, numpy=array([0.01709019, 3.6097233 ], dtype=float32)>, logits=<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-2.038928 ,  2.0217621],
       [-1.6320709,  1.9502203]], dtype=float32)>, hidden_states=None, attentions=None)


Models are standard torch.nn.Module or tf.keras.Model so you can use them in your usual training loop. 🤗 Transformers also provides a Trainer class to help with your training in PyTorch (taking care of things such as distributed training, mixed precision, etc.) whereas you can leverage the fit() method in Keras.

In [18]:
pt_save_directory = './tf_save_pretrained'
tokenizer.save_pretrained(pt_save_directory)
tf_model.save_pretrained(pt_save_directory)

You can then load this model back using the AutoModel.from_pretrained() method by passing the directory name instead of the model name. One cool feature of 🤗 Transformers is that you can easily switch between PyTorch and TensorFlow: any model saved as before can be loaded back either in PyTorch or TensorFlow.

In [20]:
from transformers import TFAutoModel
tokenizer = AutoTokenizer.from_pretrained(pt_save_directory)
tf_model = TFAutoModel.from_pretrained(pt_save_directory, from_pt=False)

Some layers from the model checkpoint at ./tf_save_pretrained were not used when initializing TFDistilBertModel: ['dropout_57', 'classifier', 'pre_classifier']
- This IS expected if you are initializing TFDistilBertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFDistilBertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
All the layers of TFDistilBertModel were initialized from the model checkpoint at ./tf_save_pretrained.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFDistilBertModel for predictions without further training.


In [21]:
tf_outputs = tf_model(tf_batch, output_hidden_states=True, output_attentions=True)
all_hidden_states =  tf_outputs.hidden_states
all_attentions = tf_outputs.attentions

# **Accessing the code**
The AutoModel and AutoTokenizer classes are just shortcuts that will automatically work with any pretrained model. Behind the scenes, the library has one model class per combination of architecture plus class, so the code is easy to access and tweak if you need to.

In [22]:
from transformers import DistilBertTokenizer, TFDistilBertForSequenceClassification
model_name = "distilbert-base-uncased-finetuned-sst-2-english"
model = TFDistilBertForSequenceClassification.from_pretrained(model_name)
tokenizer = DistilBertTokenizer.from_pretrained(model_name)

Some layers from the model checkpoint at distilbert-base-uncased-finetuned-sst-2-english were not used when initializing TFDistilBertForSequenceClassification: ['dropout_19']
- This IS expected if you are initializing TFDistilBertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFDistilBertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some layers of TFDistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased-finetuned-sst-2-english and are newly initialized: ['dropout_115']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


# **Customizing the model**
If you want to change how the model itself is built, you can define a custom configuration class. Each architecture comes with its own relevant configuration. For example, DistilBertConfig allows you to specify parameters such as the hidden dimension, dropout rate, etc for DistilBERT. If you do core modifications, like changing the hidden size, you won’t be able to use a pretrained model anymore and will need to train from scratch. You would then instantiate the model directly from this configuration.

In [23]:
from transformers import DistilBertConfig, DistilBertTokenizer, TFDistilBertForSequenceClassification
config = DistilBertConfig(n_heads=8, dim=512, hidden_dim=4*512)
tokenizer = DistilBertTokenizer.from_pretrained('distilbert-base-uncased')
model = TFDistilBertForSequenceClassification(config)

Downloading:   0%|          | 0.00/226k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/28.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/455k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/483 [00:00<?, ?B/s]

# **Distillbert**
DistilBERT is a transformers model, smaller and faster than BERT, which was pretrained on the same corpus in a self-supervised fashion, using the BERT base model as a teacher. This means it was pretrained on the raw texts only, with no humans labelling them in any way (which is why it can use lots of publicly available data) with an automatic process to generate inputs and labels from those texts using the BERT base model.

In [41]:
from transformers import DistilBertConfig, DistilBertTokenizer, TFDistilBertForSequenceClassification
model_name = "distilbert-base-uncased"
model = TFDistilBertForSequenceClassification.from_pretrained(model_name, num_labels=10)
tokenizer = DistilBertTokenizer.from_pretrained(model_name)

Some layers from the model checkpoint at distilbert-base-uncased were not used when initializing TFDistilBertForSequenceClassification: ['activation_13', 'vocab_projector', 'vocab_transform', 'vocab_layer_norm']
- This IS expected if you are initializing TFDistilBertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFDistilBertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some layers of TFDistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['dropout_175', 'classifier', 'pre_classifier']
You should probably TRAIN this model on a down-stream task to be able to use 

For something that only changes the head of the model (for instance, the number of labels), you can still use a pretrained model for the body. For instance, let’s define a classifier for 10 different labels using a pretrained body. Instead of creating a new configuration with all the default values just to change the number of labels, we can instead pass any argument a configuration would take to the from_pretrained method and it will update the default configuration appropriately.

In [42]:
print(tokenizer)

PreTrainedTokenizer(name_or_path='distilbert-base-uncased', vocab_size=30522, model_max_len=512, is_fast=False, padding_side='right', special_tokens={'unk_token': '[UNK]', 'sep_token': '[SEP]', 'pad_token': '[PAD]', 'cls_token': '[CLS]', 'mask_token': '[MASK]'})


In [43]:
classifier = pipeline('sentiment-analysis', model=model, tokenizer=tokenizer)

In [44]:
classifier('You are too good')

[{'label': 'LABEL_0', 'score': 0.1092192605137825}]

In [45]:
classifier('You are very good')

[{'label': 'LABEL_0', 'score': 0.11001115292310715}]

In [46]:
classifier('Mumbai based engineering firm Edifice Engineering has received a letter of intent from realty developer Supertech for demolishing its twin towers in Noida. ')

[{'label': 'LABEL_3', 'score': 0.112758569419384}]